editblogposts:
    pattern: /edit/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/BlogPost:editBlogPosts }
    methods:  [GET,POST]

addblogposts:
    pattern: /add
    defaults: { _controller: XvolutionsAdminBundle:Admin/BlogPost:addBlogPosts }
    methods:  [GET,POST]

optionblogposts:
    pattern: /{option}/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/BlogPost:blogPosts, option: 0, id: 0 }
    methods:  [DELETE,POST]

blogposts:
    pattern: /
    defaults: { _controller: XvolutionsAdminBundle:Admin/BlogPost:blogPosts, current_page: 1 }
    methods:  [GET]

blogposts_current:
    pattern: /{current_page}
    defaults: { _controller: XvolutionsAdminBundle:Admin/BlogPost:blogPosts, current_page: 1 }
    methods:  [GET]
    requirements:
        current_page:  \d+