editblogposts:
    path: /edit/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/BlogPost:editBlogPosts }
    methods:  [GET,POST]

addblogposts:
    path: /add
    defaults: { _controller: XvolutionsAdminBundle:Admin/BlogPost:addBlogPosts }
    methods:  [GET,POST]

optionblogposts:
    path: /{option}/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/BlogPost:blogPosts, option: 0, id: 0 }
    methods:  [DELETE,POST]

blogposts:
    path: /
    defaults: { _controller: XvolutionsAdminBundle:Admin/BlogPost:blogPosts, current_page: 1 }
    methods:  [GET]

blogposts_current:
    path: /{current_page}
    defaults: { _controller: XvolutionsAdminBundle:Admin/BlogPost:blogPosts, current_page: 1 }
    methods:  [GET]
    requirements:
        current_page:  \d+