editlanguages:
    path: /edit/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Languages:editlanguages }
    methods:  [GET,POST]

addlanguages:
    path: /add
    defaults: { _controller: XvolutionsAdminBundle:Admin/Languages:addlanguages }
    methods:  [GET,POST]

optionlanguages:
    path: /{option}/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Languages:languages, option: 0, id: 0 }
    methods:  [DELETE]

languages:
    path: /
    defaults: { _controller: XvolutionsAdminBundle:Admin/Languages:languages }
    methods:  [GET]