menu:
    path: /
    defaults: { _controller: XvolutionsAdminBundle:Admin/Menu:menu }
    methods:  [GET]

menuupdate:
    path: /update
    defaults: { _controller: XvolutionsAdminBundle:Admin/Menu:update }
    methods:  [POST]
