editpages:
    path: /edit/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Pages:editpages }
    methods:  [GET,POST]

addpages:
    path: /add
    defaults: { _controller: XvolutionsAdminBundle:Admin/Pages:addpages }
    methods:  [GET,POST]

pagesoption:
    path: /{option}/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Pages:pages, option: 0, id: 0 }
    methods:  [DELETE,POST]

pages:
    path: /
    defaults: { _controller: XvolutionsAdminBundle:Admin/Pages:pages, current_page: 1 }
    methods:  [GET]

pages_current:
    path: /{current_page}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Pages:pages, current_page: 1 }
    methods:  [GET]
    requirements:
        current_page:  \d+
