editpages:
    pattern: /edit/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Pages:editpages }
    methods:  [GET,POST]

addpages:
    pattern: /add
    defaults: { _controller: XvolutionsAdminBundle:Admin/Pages:addpages }
    methods:  [GET,POST]

pagesoption:
    pattern: /{option}/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Pages:pages, option: 0, id: 0 }
    methods:  [DELETE]

pages:
    pattern: /
    defaults: { _controller: XvolutionsAdminBundle:Admin/Pages:pages, current_page: 1 }
    methods:  [GET]

pages_current:
    pattern: /{current_page}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Pages:pages, current_page: 1 }
    methods:  [GET]
    requirements:
        current_page:  \d+