editroles:
    path: /edit/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Roles:editroles }
    methods:  [GET,POST]

addroles:
    path: /add
    defaults: { _controller: XvolutionsAdminBundle:Admin/Roles:addroles }
    methods:  [GET,POST]

optionroles:
    path: /{option}/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Roles:roles, option: 0, id: 0 }
    methods:  [DELETE]

roles:
    path: /
    defaults: { _controller: XvolutionsAdminBundle:Admin/Roles:roles }
    methods:  [GET]