editsections:
    path: /edit/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Sections:editsection }
    methods:  [GET,POST]

addsections:
    path: /add
    defaults: { _controller: XvolutionsAdminBundle:Admin/Sections:addsection }
    methods:  [GET,POST]

optionsections:
    path: /{option}/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Sections:sections, option: 0, id: 0 }
    methods:  [DELETE]

sections:
    path: /
    defaults: { _controller: XvolutionsAdminBundle:Admin/Sections:sections }
    methods:  [GET]