edittags:
    path: /edit/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Tag:edittags }
    methods:  [GET,POST]

addtags:
    path: /add
    defaults: { _controller: XvolutionsAdminBundle:Admin/Tag:addtags }
    methods:  [GET,POST]

optiontags:
    path: /{option}/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Tag:tags, option: 0, id: 0 }
    methods:  [DELETE]

tags:
    path: /
    defaults: { _controller: XvolutionsAdminBundle:Admin/Tag:tags }
    methods:  [GET]