security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
        default:
            algorithm: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [user_db]
        user_db:
            entity: { class: Xvolutions\AdminBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:   ^/admin/
            anonymous: ~
            form_login:
                csrf_provider: form.csrf_provider
                login_path: login
                check_path: login_check
                always_use_default_target_path: true
                default_target_path: /admin/backoffice
            logout:
                path:   logout
                target: /admin/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/backoffice, roles: ROLE_ADMIN }
