login:
    pattern:  /
    defaults: { _controller: XvolutionsAdminBundle:Security:login }

login_check:
    pattern: /login_check
    
logout:
   pattern:   /logout

recover:
    pattern:  /recover
    defaults: { _controller: XvolutionsAdminBundle:Security:recover }

backoffice:
    pattern: /backoffice
    defaults: { _controller: XvolutionsAdminBundle:Admin:backoffice }

setup:
    pattern: /setup
    defaults: { _controller: XvolutionsAdminBundle:Admin:setup }

editpages:
    pattern: /pages/edit/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Pages:editpages }

pages:
    pattern: /pages
    defaults: { _controller: XvolutionsAdminBundle:Admin/Pages:pages }

addpages:
    pattern: /pages/add
    defaults: { _controller: XvolutionsAdminBundle:Admin/Pages:addpages }

sectionsedit:
    pattern: /sections/edit/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Sections:editsection }
    methods:  [GET,POST]

sectionsoption:
    pattern: /sections/{option}/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Sections:sections, options: 0, id: 0 }
    methods:  [GET]

sections:
    pattern: /sections
    defaults: { _controller: XvolutionsAdminBundle:Admin/Sections:sections }
    methods:  [GET]

sectionsadd:
    pattern: /sections/add
    defaults: { _controller: XvolutionsAdminBundle:Admin/Sections:addsection }
    methods:  [GET,POST]

