login:
    pattern:  /
    defaults: { _controller: XvolutionsAdminBundle:Security:login }
    methods:  [GET,POST]

login_check:
    pattern: /login_check
    
logout:
   pattern:   /logout

recover:
    pattern:  /recover
    defaults: { _controller: XvolutionsAdminBundle:Security:recover }
    methods:  [GET,POST]

backoffice:
    pattern: /backoffice
    defaults: { _controller: XvolutionsAdminBundle:Admin:backoffice }
    methods:  [GET]

setup:
    pattern: /setup
    defaults: { _controller: XvolutionsAdminBundle:Admin:setup }
    methods:  [GET]

### PAGES ###

XvolutionsAdminBundle_pages:
        resource: "@XvolutionsAdminBundle/Resources/config/routing/pages.yml"
        prefix:   /pages

### SECTIONS ###

XvolutionsAdminBundle_sections:
        resource: "@XvolutionsAdminBundle/Resources/config/routing/sections.yml"
        prefix:   /sections

### LANGUAGES ###

XvolutionsAdminBundle_languages:
        resource: "@XvolutionsAdminBundle/Resources/config/routing/languages.yml"
        prefix:   /languages

### USERS ###

XvolutionsAdminBundle_users:
        resource: "@XvolutionsAdminBundle/Resources/config/routing/users.yml"
        prefix:   /users

### ROLES ###

XvolutionsAdminBundle_roles:
        resource: "@XvolutionsAdminBundle/Resources/config/routing/roles.yml"
        prefix:   /roles

### BLOG POSTS ###

XvolutionsAdminBundle_blog_posts:
        resource: "@XvolutionsAdminBundle/Resources/config/routing/blogpost.yml"
        prefix:   /blog/posts

### FILES ###

XvolutionsAdminBundle_files:
        resource: "@XvolutionsAdminBundle/Resources/config/routing/file.yml"
        prefix:   /files
