login:
    pattern:  /
    defaults: { _controller: XvolutionsAdminBundle:Security:login }

login_check:
    pattern: /login_check
    
logout:
   pattern:   /logout

recover:
    pattern:  /recover
    defaults: { _controller: XvolutionsAdminBundle:Security:recover }

backoffice:
    pattern: /backoffice
    defaults: { _controller: XvolutionsAdminBundle:Admin:backoffice }

setup:
    pattern: /setup
    defaults: { _controller: XvolutionsAdminBundle:Admin:setup }

pages:
    pattern: /pages
    defaults: { _controller: XvolutionsAdminBundle:Admin:pages }

sections:
    pattern: /sections
    defaults: { _controller: XvolutionsAdminBundle:Admin:sections }

sectionsoption:
    pattern: /sections/{option}/{ids}
    defaults: { _controller: XvolutionsAdminBundle:Admin:sectionsoptions, ids: 0 }