login:
    pattern:  /
    defaults: { _controller: XvolutionsAdminBundle:Security:login }

login_check:
    pattern: /login_check
    
logout:
   pattern:   /logout

recover:
    pattern:  /recover
    defaults: { _controller: XvolutionsAdminBundle:Security:recover }

backoffice:
    pattern: /backoffice
    defaults: { _controller: XvolutionsAdminBundle:Admin:backoffice }

setup:
    pattern: /setup
    defaults: { _controller: XvolutionsAdminBundle:Admin:setup }

### PAGES ###

editpages:
    pattern: /pages/edit/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Pages:editpages }

addpages:
    pattern: /pages/add
    defaults: { _controller: XvolutionsAdminBundle:Admin/Pages:addpages }

pagesoption:
    pattern: /pages/{option}/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Pages:pages, options: 0, id: 0 }
    methods:  [GET]

pages:
    pattern: /pages
    defaults: { _controller: XvolutionsAdminBundle:Admin/Pages:pages }

### SECTIONS ###

editsections:
    pattern: /sections/edit/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Sections:editsection }
    methods:  [GET,POST]

addsections:
    pattern: /sections/add
    defaults: { _controller: XvolutionsAdminBundle:Admin/Sections:addsection }
    methods:  [GET,POST]

optionsections:
    pattern: /sections/{option}/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Sections:sections, options: 0, id: 0 }
    methods:  [GET]

sections:
    pattern: /sections
    defaults: { _controller: XvolutionsAdminBundle:Admin/Sections:sections }
    methods:  [GET]

### LANGUAGES ###

editlanguages:
    pattern: /languages/edit/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Languages:editlanguages }
    methods:  [GET,POST]

addlanguages:
    pattern: /languages/add
    defaults: { _controller: XvolutionsAdminBundle:Admin/Languages:addlanguages }
    methods:  [GET,POST]

optionlanguages:
    pattern: /languages/{option}/{id}
    defaults: { _controller: XvolutionsAdminBundle:Admin/Languages:languages, options: 0, id: 0 }
    methods:  [GET]

languages:
    pattern: /languages
    defaults: { _controller: XvolutionsAdminBundle:Admin/Languages:languages }
    methods:  [GET]