parameters:
    xvolutions_admin.misc.class: Xvolutions\AdminBundle\Helpers\Misc
    xvolutions_admin.misc.arguments: fetchGravatar

services:
    xvolutions_admin.misc:
        class: %xvolutions_admin.misc.class%
        arguments: [%xvolutions_admin.misc.arguments%]
