Xvolutions\AdminBundle\Entity\File:
    properties:
        name:
            - NotBlank: ~
        file_name:
            - NotBlank: ~
            - File:
                maxSize: 3M
                maxSizeMessage: O tamanho máximo do ficheiro é de 3Mb.
                mimeTypes: [image/jpeg, image/gif, image/png, image/tiff, application/pdf, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, text/plain]
                mimeTypesMessage: Só é possível seleccionar imagens do tipo JPG, GIT, PNG, TIFF e documentos do tipo PDF, DOC, DOCX e TXT.
        date:
            - NotBlank: ~
            - DateTime: ~
        size:
            - NotBlank: ~