parameters:
#    cleverti_cti_login.example.class: Cleverti\CTILoginBundle\Example

services:
#    cleverti_cti_login.example:
#        class: %cleverti_cti_login.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
